"""Lambda handler for the Generate phase of GateShift pipeline."""

from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone

import boto3
import yaml

from pipeline_common import mark_failed

s3 = boto3.client("s3")
dynamodb = boto3.resource("dynamodb")
table = dynamodb.Table(os.environ.get("MIGRATIONS_TABLE", "GateShiftMigrations"))


def handler(event: dict, context) -> dict:
    """
    Generate deployable SAM template from migration plan.

    Input event (from Step Functions):
        - migration_id: str
        - bucket: str
        - target_api_type: str
    """
    migration_id = event["migration_id"]

    try:
        return _run(event, migration_id)
    except Exception as exc:
        mark_failed(migration_id, "Generation stage failed")
        print(f"Generator failed for {migration_id}: {exc}")
        raise


def _run(event: dict, migration_id: str) -> dict:
    bucket = event["bucket"]

    _update_status(migration_id, "GENERATING")

    # Load migration plan
    plan = json.loads(
        s3.get_object(
            Bucket=bucket,
            Key=f"migrations/{migration_id}/migration_plan.json",
        )["Body"].read()
    )

    # Load normalized config for route/path detail (used by the OpenAPI spec).
    # It is optional: if it is missing we still produce the other artifacts.
    try:
        normalized = json.loads(
            s3.get_object(
                Bucket=bucket,
                Key=f"migrations/{migration_id}/normalized.json",
            )["Body"].read()
        )
    except s3.exceptions.NoSuchKey:
        normalized = {}

    # Generate SAM template
    sam_template = _generate_sam_template(plan)

    # Generate Lambda authorizer code if needed
    authorizer_code = _generate_authorizer_code(plan)

    # Store SAM template
    s3.put_object(
        Bucket=bucket,
        Key=f"migrations/{migration_id}/output/template.yaml",
        Body=yaml.dump(sam_template, default_flow_style=False, sort_keys=False),
        ContentType="text/yaml",
    )

    # Store authorizer code if generated
    if authorizer_code:
        s3.put_object(
            Bucket=bucket,
            Key=f"migrations/{migration_id}/output/authorizer/index.py",
            Body=authorizer_code,
            ContentType="text/x-python",
        )
        s3.put_object(
            Bucket=bucket,
            Key=f"migrations/{migration_id}/output/authorizer/requirements.txt",
            Body="PyJWT>=2.8\ncryptography>=41.0\n",
            ContentType="text/plain",
        )

    # Generate a human-readable migration report
    report_md = _generate_report_markdown(plan)
    s3.put_object(
        Bucket=bucket,
        Key=f"migrations/{migration_id}/output/migration-report.md",
        Body=report_md,
        ContentType="text/markdown",
    )

    # Generate an OpenAPI 3.0 spec reconstructed from the source routes
    openapi_spec = _generate_openapi_spec(plan, normalized)
    s3.put_object(
        Bucket=bucket,
        Key=f"migrations/{migration_id}/output/openapi.yaml",
        Body=yaml.dump(openapi_spec, default_flow_style=False, sort_keys=False),
        ContentType="text/yaml",
    )

    return {
        "statusCode": 200,
        "migration_id": migration_id,
        "bucket": bucket,
        "template_key": f"migrations/{migration_id}/output/template.yaml",
        "openapi_key": f"migrations/{migration_id}/output/openapi.yaml",
        "has_authorizer": authorizer_code is not None,
    }


def _generate_sam_template(plan: dict) -> dict:
    """Generate AWS SAM template from migration plan."""
    target_type = plan.get("target_api_type", "REST")

    template = {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Transform": "AWS::Serverless-2016-10-31",
        "Description": "Migrated API — Generated by GateShift",
        "Globals": {
            "Api": {
                "Cors": {
                    "AllowMethods": "'GET,POST,PUT,DELETE,OPTIONS'",
                    "AllowHeaders": "'Content-Type,Authorization,X-Api-Key'",
                    "AllowOrigin": "'*'",
                }
            }
        },
        "Resources": {},
        "Outputs": {},
    }

    for api in plan.get("apis", []):
        api_name = api.get("name", "DefaultApi")
        logical_id = _sanitize_logical_id(api_name)

        # Determine auth config
        auth_config = _build_auth_config(api, logical_id)

        # Create API resource
        if target_type == "REST":
            template["Resources"][f"{logical_id}Api"] = {
                "Type": "AWS::Serverless::Api",
                "Properties": {
                    "StageName": "prod",
                    "Description": f"Migrated from Kong service: {api_name}",
                    **({"Auth": auth_config} if auth_config else {}),
                },
            }
        else:
            template["Resources"][f"{logical_id}HttpApi"] = {
                "Type": "AWS::Serverless::HttpApi",
                "Properties": {
                    "StageName": "prod",
                    "Description": f"Migrated from Kong service: {api_name}",
                    "CorsConfiguration": {
                        "AllowMethods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
                        "AllowHeaders": ["Content-Type", "Authorization"],
                        "AllowOrigins": ["*"],
                    },
                },
            }

        # Create Usage Plan if rate limiting detected
        if _has_rate_limiting(api):
            rate_config = _extract_rate_config(api)
            template["Resources"][f"{logical_id}UsagePlan"] = {
                "Type": "AWS::ApiGateway::UsagePlan",
                "Properties": {
                    "UsagePlanName": f"{api_name}-usage-plan",
                    "Description": f"Rate limiting for {api_name}",
                    "Throttle": rate_config,
                    "ApiStages": [
                        {
                            "ApiId": {"Ref": f"{logical_id}Api"},
                            "Stage": "prod",
                        }
                    ],
                },
            }

        # Create Lambda Authorizer if needed
        authorizer_type = api.get("authorizer_type", "NONE")
        if authorizer_type == "LAMBDA":
            template["Resources"][f"{logical_id}AuthorizerFunction"] = {
                "Type": "AWS::Serverless::Function",
                "Properties": {
                    "Handler": "index.handler",
                    "Runtime": "python3.12",
                    "CodeUri": "./authorizer/",
                    "Description": f"Token authorizer for {api_name}",
                    "Timeout": 10,
                    "MemorySize": 256,
                },
            }

        # Add output
        api_ref = f"{logical_id}Api" if target_type == "REST" else f"{logical_id}HttpApi"
        template["Outputs"][f"{logical_id}Endpoint"] = {
            "Description": f"{api_name} API endpoint",
            "Value": {
                "Fn::Sub": f"https://${{{api_ref}}}.execute-api.${{AWS::Region}}.amazonaws.com/prod"
            },
        }

    return template


def _build_auth_config(api: dict, logical_id: str) -> dict | None:
    """Build SAM Auth configuration from migration plan."""
    authorizer_type = api.get("authorizer_type", "NONE")

    if authorizer_type == "NONE":
        return None
    elif authorizer_type == "API_KEY":
        return {
            "ApiKeyRequired": True,
            "UsagePlan": {"CreateUsagePlan": "PER_API"},
        }
    elif authorizer_type == "LAMBDA":
        return {
            "DefaultAuthorizer": "TokenAuthorizer",
            "Authorizers": {
                "TokenAuthorizer": {
                    "FunctionArn": {
                        "Fn::GetAtt": [f"{logical_id}AuthorizerFunction", "Arn"]
                    },
                    "Identity": {
                        "Header": "Authorization",
                        "ReauthorizeEvery": 300,
                    },
                }
            },
        }
    elif authorizer_type == "COGNITO":
        return {
            "DefaultAuthorizer": "CognitoAuthorizer",
            "Authorizers": {
                "CognitoAuthorizer": {
                    "UserPoolArn": "!Ref CognitoUserPoolArn",  # Parameter needed
                }
            },
        }

    return None


def _has_rate_limiting(api: dict) -> bool:
    """Check if any feature mapping indicates rate limiting."""
    for mapping in api.get("feature_mappings", []):
        if mapping.get("source_plugin_name") in ("rate-limiting", "response-ratelimiting"):
            return True
    return False


def _extract_rate_config(api: dict) -> dict:
    """Extract throttle settings from feature mappings."""
    # Default reasonable values
    return {
        "RateLimit": 100,
        "BurstLimit": 200,
    }


def _generate_authorizer_code(plan: dict) -> str | None:
    """Generate Lambda authorizer code if any API needs it."""
    needs_authorizer = any(
        api.get("authorizer_type") == "LAMBDA" for api in plan.get("apis", [])
    )

    if not needs_authorizer:
        return None

    return '''"""GateShift-generated Lambda Authorizer."""

import json
import os

import jwt  # PyJWT


def handler(event, context):
    """
    Token-based Lambda Authorizer.
    Validates JWT from Authorization header and returns IAM policy.
    """
    token = event.get("authorizationToken", "")
    method_arn = event.get("methodArn", "")

    # Remove "Bearer " prefix if present
    if token.lower().startswith("bearer "):
        token = token[7:]

    try:
        # TODO: Configure these from environment variables
        secret = os.environ.get("JWT_SECRET", "your-secret-key")
        algorithms = ["HS256"]

        decoded = jwt.decode(token, secret, algorithms=algorithms)

        principal_id = decoded.get("sub", "user")
        return _generate_policy(principal_id, "Allow", method_arn)

    except jwt.ExpiredSignatureError:
        print("Token expired")
        return _generate_policy("user", "Deny", method_arn)
    except jwt.InvalidTokenError as e:
        print(f"Invalid token: {e}")
        return _generate_policy("user", "Deny", method_arn)


def _generate_policy(principal_id: str, effect: str, method_arn: str) -> dict:
    """Generate IAM policy document for API Gateway."""
    # Extract the API Gateway ARN base (everything before the method)
    arn_parts = method_arn.split(":")
    region = arn_parts[3]
    account_id = arn_parts[4]
    api_gateway_arn = arn_parts[5].split("/")
    api_id = api_gateway_arn[0]
    stage = api_gateway_arn[1]

    # Allow all methods on this API for this principal
    resource_arn = f"arn:aws:execute-api:{region}:{account_id}:{api_id}/{stage}/*"

    return {
        "principalId": principal_id,
        "policyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "execute-api:Invoke",
                    "Effect": effect,
                    "Resource": resource_arn,
                }
            ],
        },
        "context": {
            "principalId": principal_id,
        },
    }
'''


def _generate_report_markdown(plan: dict) -> str:
    """Generate human-readable migration report."""
    target_type = plan.get("target_api_type", "REST")
    reasoning = plan.get("target_api_type_reasoning", "")
    summary = plan.get("summary", {})
    warnings = plan.get("warnings", [])

    lines = [
        "# GateShift Migration Report",
        "",
        f"**Target API Type:** {target_type} API",
        f"**Reasoning:** {reasoning}",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Direct Mappings | {summary.get('direct_count', 0)} |",
        f"| Lambda Required | {summary.get('lambda_count', 0)} |",
        f"| Alternative Architecture | {summary.get('alternative_count', 0)} |",
        f"| Gaps (No Equivalent) | {summary.get('gap_count', 0)} |",
        f"| Estimated Effort | {summary.get('estimated_effort_hours', 0)} hours |",
        "",
    ]

    # API details
    for api in plan.get("apis", []):
        lines.append(f"## API: {api.get('name', 'Unknown')}")
        lines.append("")
        lines.append(f"**Authorizer:** {api.get('authorizer_type', 'NONE')}")
        lines.append("")
        lines.append("### Feature Mappings")
        lines.append("")
        lines.append("| Source Plugin | AWS Equivalent | Type | Notes |")
        lines.append("|---|---|---|---|")

        for mapping in api.get("feature_mappings", []):
            lines.append(
                f"| {mapping.get('source_plugin_name', '')} "
                f"| {mapping.get('aws_equivalent', '')} "
                f"| {mapping.get('mapping_type', '')} "
                f"| {mapping.get('implementation_notes', '')} |"
            )
        lines.append("")

    # Warnings
    if warnings:
        lines.append("## Warnings")
        lines.append("")
        for warning in warnings:
            lines.append(f"- ⚠️ {warning}")
        lines.append("")

    # Next steps
    lines.extend([
        "## Next Steps",
        "",
        "1. Review the generated `template.yaml`",
        "2. Adjust any parameter values (backend URLs, secrets)",
        "3. If a Lambda authorizer was generated, configure `JWT_SECRET` environment variable",
        "4. Deploy with: `sam build && sam deploy --guided`",
        "5. Test with synthetic traffic before cutting over production",
        "",
        "---",
        "*Generated by GateShift*",
    ])

    return "\n".join(lines)


def _generate_openapi_spec(plan: dict, normalized: dict) -> dict:
    """Reconstruct an OpenAPI 3.0 spec from the source routes.

    Paths and methods come from the normalized config (the parser's IR), while
    the auth scheme per API is taken from the migration plan so the spec
    reflects the authorizer that will be generated in the SAM template.
    """
    target_type = plan.get("target_api_type", "REST")

    # Map source API name -> authorizer type decided by the analyzer/plan.
    auth_by_api = {
        api.get("name", ""): api.get("authorizer_type", "NONE")
        for api in plan.get("apis", [])
    }

    spec: dict = {
        "openapi": "3.0.1",
        "info": {
            "title": "Migrated API — Generated by GateShift",
            "version": "1.0.0",
            "description": (
                "OpenAPI definition reconstructed from the source gateway "
                f"configuration during migration to a {target_type} API Gateway."
            ),
        },
        "paths": {},
        "components": {"securitySchemes": {}},
    }

    security_schemes: dict = spec["components"]["securitySchemes"]

    for api in normalized.get("apis", []):
        api_name = api.get("name", "")
        authorizer_type = auth_by_api.get(api_name, "NONE")
        scheme_name = _security_scheme_for(authorizer_type, security_schemes)

        backend = api.get("backend", {}) or {}
        backend_url = backend.get("url", "")

        for route in api.get("routes", []):
            methods = route.get("methods") or ["GET"]
            for raw_path in route.get("paths") or []:
                path = _normalize_openapi_path(raw_path)
                path_item = spec["paths"].setdefault(path, {})
                for method in methods:
                    operation = {
                        "summary": f"{method.upper()} {path}",
                        "description": _operation_description(
                            api_name, route, backend_url
                        ),
                        "responses": {"200": {"description": "Successful response"}},
                    }
                    if api_name:
                        operation["tags"] = [api_name]
                    if scheme_name:
                        operation["security"] = [{scheme_name: []}]
                    path_item[method.lower()] = operation

    # Drop empty components so the spec stays clean when there is no auth.
    if not security_schemes:
        del spec["components"]

    return spec


def _security_scheme_for(authorizer_type: str, security_schemes: dict) -> str | None:
    """Register (once) and return the OpenAPI security scheme for an authorizer."""
    if authorizer_type == "API_KEY":
        name = "ApiKeyAuth"
        security_schemes.setdefault(
            name, {"type": "apiKey", "name": "x-api-key", "in": "header"}
        )
        return name
    if authorizer_type in ("LAMBDA", "COGNITO"):
        name = "BearerAuth"
        security_schemes.setdefault(
            name, {"type": "http", "scheme": "bearer", "bearerFormat": "JWT"}
        )
        return name
    return None


def _normalize_openapi_path(raw_path: str) -> str:
    """Convert a Kong route path into an OpenAPI-style path.

    Kong prefixes regex paths with "~" and may use named captures such as
    "(?<id>\\d+)"; convert those to OpenAPI path parameters like "{id}".
    """
    path = (raw_path or "").strip()
    if path.startswith("~"):
        path = path[1:]
    # (?<name>...) and (?P<name>...) -> {name}
    path = re.sub(
        r"\(\?P?<([a-zA-Z_][a-zA-Z0-9_]*)>[^)]*\)",
        r"{\1}",
        path,
    )
    if not path.startswith("/"):
        path = "/" + path
    return path


def _operation_description(api_name: str, route: dict, backend_url: str) -> str:
    """Build a short operation description from source metadata."""
    parts = []
    if api_name:
        parts.append(f"Source service: {api_name}.")
    route_name = route.get("name")
    if route_name:
        parts.append(f"Route: {route_name}.")
    if backend_url:
        parts.append(f"Upstream: {backend_url}.")
    return " ".join(parts)


def _sanitize_logical_id(name: str) -> str:
    """Convert a name to a valid CloudFormation logical ID."""
    # Remove non-alphanumeric, capitalize words
    parts = re.split(r"[^a-zA-Z0-9]", name)
    return "".join(part.capitalize() for part in parts if part)


def _update_status(migration_id: str, status: str) -> None:
    """Update migration status in DynamoDB."""
    table.update_item(
        Key={"migration_id": migration_id},
        UpdateExpression="SET #s = :status, updated_at = :ts",
        ExpressionAttributeNames={"#s": "status"},
        ExpressionAttributeValues={
            ":status": status,
            ":ts": datetime.now(timezone.utc).isoformat(),
        },
    )
